#!/usr/bin/env bash

prefix=$(echo $1 | cut -c1-3)
if [[ "$prefix" == "git" ]]; then
  owner=$(echo $1 | cut -d':' -f 2 | cut -d'/' -f 1)
else
  owner=$(echo $1 | cut -d'/' -f 4)
  repo=$(echo $1 | cut -d'/' -f 5)
  repo=$(echo $repo | cut -d'.' -f 1)
  infostellar=1
fi

mkdir -p $owner && cd $owner

git clone $1

if [ infostellar ]; then
  cd $repo
  git config user.email "jim@infostellarinc.com"
fi

