#!/usr/bin/env bash

case $1 in
    "sleep")
        i3lock && sudo systemctl suspend
        ;;
    "shutdown")
        sudo shutdown now
        ;;
    "reboot")
        sudo reboot now
        ;;
    *)
        echo "Valid options are 'sleep', 'shutdown', and 'reboot'"
        ;;
esac
